### ISSUE TITLE
Max Packet Size of 256 causes errors on Mac OS X

### ISSUE THREAD

**Issue by DisasterAreaDesigns** [gbevin/SendMIDI#10]
Due to the way Mac OS handles sending USB MIDI to certain interfaces, having a max packet size of 256 bytes will cause the 256th byte in a long sysex transfer to be skipped.  I've been able to work around this issue by manually changing the value in juce_mac_CoreMidi.cpp from 256 to 255. 

More details here:

https://forum.juce.com/t/problem-with-sysex-transfer-over-usb-midi-on-mac/9830

Would it be possible to make the packet size a command line option?  For most applications, the default works perfectly but it would be nice to be able to specify that at run time.

**Comment by gbevin** [comment]
If JUCE makes it possible to set this without having to fork JUCE, I'll add it to the options in SendMIDI. I don't really want to maintain a separate JUCE fork just for this.

**Comment by DisasterAreaDesigns** [comment]
Juce has that value as a constant inside the MidiOutput::sendMessageNow() function so it will never even look at anything in the global scope.  The right way to handle this is by having the folks at Roli fix it in JUCE, I'll go post this over there.
