### ISSUE TITLE
Created virtual port does not work, No software synth.

### ISSUE THREAD

**Issue by PaulMcClernan** [gbevin/SendMIDI#11]
Creates virtual port on Mac OS 10.11.6, but does not seem to send notes on to the port. Ports created with Apple Audio MIDI setup work as expected.
Also list command does not show port from the OS software synth (Apple DLS Synth).

BTW, thanks for putting this out, very useful as it is.

**Comment by gbevin** [comment]
Hi Paul,

I can't reproduce your report. When creating a virtual MIDI port though, it can take time for it to appear in other applications, or you might even have to select it manually. One way to do this, is by adding a relative timestamp before your first note command, as such: `sendmidi virt sm +10.000 on 23 45`

Afaik, the Apple DLS Synth is just an AU, it doesn't create its own MIDI port, so SendMIDI can't send to the DLS Synth directly.

Take care,

Geert
