### ISSUE TITLE
Example uses of hex and raw

### ISSUE THREAD

**Issue by cyrusadkisson** [gbevin/SendMIDI#12]
This program has been great for debugging wth is going on with my programs and systems. However, I had to hunt and peck to figure out how do do what I was trying to do. I finally got to my answer, so here is what I found. (You'll need a decimal/hex/binary converter. Many available online.)

To use raw mode, format your commands like this:
`./sendmidi dev "Midi Through Port-0" raw 11000000 00000000`
(That is a program change on channel 1 to instrument 0 (acoustic grand piano in midi standard))

To use hex, do this. Same command as above:
./sendmidi dev "Midi Through Port-0" hex raw c0 00

Now let's say you want to do a CC bank change on channel one at LSB controller 0 to bank 3 followed by a program change to preset 4. Using this table (https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2), we see that LSB is at decimal 32 (hex 20). Program change is still c0 from above
./sendmidi dev "Midi Through Port-0" hex raw b0 20 02 c0 03

Broken down, that command is:
sendmidi →"hey sendmidi"
dev →tell device "Midi through port 0" 
hex→(btw I'm talking to you in hex)
raw →(btw I want you to send this as raw bytes)
b0 →on channel 1 
20 →to change banks
02 →to bank 3
c0 →then change programs
03 →to preset 3

You might cut/paste this into the readme file.

**Comment by gbevin** [comment]
If you want to do raw MIDI, you definitely need that research. However you could just have used the built in commands:

For instance bank select 0 with program change 3

`sendmidi dev "dev" cc 0 0 pc 3`
