### ISSUE TITLE
 Avira Virus scanner alert on sendmidi.exe

### ISSUE THREAD

**Issue by christofmuc** [gbevin/SendMIDI#13]
I'm sure this is false alarm but my Avira virus scanner prevented me from running the latest Windows release of sendmidi.exe with the "HEUR/APC (Cloud)" pattern. That seems to be a generic detection heuristic without any specific explanation. 

Anyway, I guess I'll compile SendMIDI myself now ;-)

**Comment by gbevin** [comment]
Not much I can do about that sadly
