### ISSUE TITLE
Issue with using hex/dec within a file

### ISSUE THREAD

**Issue by neunaber** [gbevin/SendMIDI#14]
I am using SendMIDI to send a file as follows:
    sendmidi.exe dev "USB Midi" file preset.txt

The file preset.txt contains the following (read using ReceiveMIDI and redirected to a file):
    system-exclusive hex 00 10 70 01 04 01 3F 41 3B 41 3E 42 2A 14 dec

However, this is what is actually sent (read using ReceiveMIDI):
    system-exclusive hex 00 0A 46 01 04 01 03 29 03 29 03 2A 02 0E dec

Omitting the "dec" at the end does work properly. Alternatively, sending this from the command line also works.

**Comment by francoisgeorgy** [comment]
I also have the same problem. With "dec" at the end of the command, the bytes sent are incorrect. Omitting "dev" fix the problem.
