### ISSUE TITLE
The i386 architecture is deprecated

### ISSUE THREAD

**Issue by hopehopez** [gbevin/SendMIDI#15]
When I install the receivemidi from gbevin/tools, it's build failed.
$ brew install gbevin/tools/sendmidi
==> Installing sendmidi from gbevin/tools
==> Downloading https://github.com/gbevin/SendMIDI/archive/1.0.13.tar.gz
Already downloaded: /Users/lex/Library/Caches/Homebrew/downloads/c9bb5b7e6d4bc6d14383b5ed68f098ed24b4fa68737f3cfb8e04ce46a626ec54--SendMIDI-1.0.13.tar.gz
==> xcodebuild -project ./Builds/MacOSX/sendmidi.xcodeproj -configuration Release SYMROOT=build
Last 15 lines from /Users/lex/Library/Logs/Homebrew/sendmidi/01.xcodebuild:
-configuration
Release
SYMROOT=build

Build settings from command line:
SYMROOT = build

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'sendmidi - ConsoleApp')

** BUILD FAILED **

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/gbevin/homebrew-tools/issues

**Comment by waipeinan** [comment]
im having identical issues..
Mac OS 10.13.6

**Comment by gbevin** [comment]
Fixed in latest repo version, will create a new release soon
