### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by pierredewilde** [gbevin/SendMIDI#16]
Test.txt:

> +00.000   channel  1   note-on           C3 127
> +01.000   channel  1   note-off          C3 127

```
$ sendmidi dev VMPK file test.txt
=> Segmentation fault: 11
```
Test.txt:

> dev VMPK
> +00.000   channel  1   note-on           C3 127
> +01.000   channel  1   note-off          C3 127

```
$ sendmidi file test.txt
=> OK
```

**Comment by gbevin** [comment]
Thanks, fixes in latest repo version.
