### ISSUE TITLE
SendMIDI panic does not use offset-middle-c (omc) value

### ISSUE THREAD

**Issue by pierredewilde** [gbevin/SendMIDI#17]
`$ sendmidi dev vmpk panic`
or
`$ sendmidi dev vmpk omc 3 panic `

correctly generates

```
channel  1   control-change    64   0
channel  1   control-change   120   0
channel  1   control-change   123   0
channel  1   note-off         C-2   0
...
channel 16   note-off          G8   0 
```

`$ sendmidi dev vmpk omc 4 panic `

should generates

```
channel  1   control-change    64   0
channel  1   control-change   120   0
channel  1   control-change   123   0
channel  1   note-off         C-1   0
...
channel 16   note-off          G9   0
```
instead of 
```
channel  1   control-change    64   0
channel  1   control-change   120   0
channel  1   control-change   123   0
channel  1   note-off         C-2   0
...
channel 16   note-off          G8   0
```

**Comment by gbevin** [comment]
I don't agree, the octave middle C is to adapt how specific notes are sent out. The Panic function sends out 128 note offs, one for each possible MIDI note in order to ensure none are still sounding. This is unrelated to the middle C.

**Comment by pierredewilde** [comment]
By changing the octave middle C, the relative position of keyboard changes from **`C-2 to G8 (omc 3)`** and from **`C-1 to G9 (omc 4)`**. What does not change is the absolute value of MIDI notes from **`0 to 127`**.

Therefore, I suggest:
```
channel  1   control-change    64   0
channel  1   control-change   120   0
channel  1   control-change   123   0
channel  1   note-off           0   0
...
channel 16   note-off         127   0  
```

**Comment by gbevin** [comment]
The same MIDI note numbers still exist, those can't change they always range from 0 to 127 and that is what is used to send out the list of note off messages in the panic command

**Comment by gbevin** [comment]
sendmidi sends this out with note numbers, what you're listing is how it's received by something else (maybe receivemidi), that is not related to how it's being sent out
