### ISSUE TITLE
Delay option for large sysex files

### ISSUE THREAD

**Issue by jorisroling** [gbevin/SendMIDI#20]
Hi,

I like using SendMIDI to send a large sysex file to a device, but SendMIDI is 'too fast'. Could we have an 'delay (ms)' option, so to slow it down a bit?

Cheers!

**Comment by astwist** [comment]
Hello, great app, I too would love to be able to add some pause between sysex packets as my device can't handle the current speed. Thanks!

**Comment by kenjwright** [comment]
+1 for same issue please! Using SysEx Librarian, between 20-40 milliseconds (configurable) between packets works for my use case.

**Comment by mmontag** [comment]
+1, this is a problem when sending any large sysex to a hardware device.

**Comment by mmontag** [comment]
Hmm, it seems that sendmidi is exceeding the MIDI speed limit of 3125 bytes/sec; only 20 sec to send a 120 KB file means about 6 KB/sec. Or maybe something else is happening, like an internal CoreMIDI buffer limit reached.

Also, sendmidi immediately exits before the transmit completes (while MIDI activity continues). Could this cause problems in shell scripting if you need to sequence commands?

**Comment by gbevin** [comment]
Fixed for next version
