### ISSUE TITLE
Send NRPN and RPN

### ISSUE THREAD

**Issue by sletz** [gbevin/SendMIDI#22]
I see that `rpn` and  `nrpn` actually send 6 controllers, like the following trace:

```
13:57:04.048	From Bus IAC 1	Control	1	101	0
13:57:04.048	From Bus IAC 1	Control	1	100	0
13:57:04.048	From Bus IAC 1	Control	1	6	12
13:57:04.048	From Bus IAC 1	Control	1	38	0
13:57:04.048	From Bus IAC 1	Control	1	101	127
13:57:04.048	From Bus IAC 1	Control	1	100	127

```
AFAICS  4 should be sent instead (see for instance http://www.philrees.co.uk/nrpnq.htm), the last 2 one should not be sent.

**Comment by gbevin** [comment]
Yes, this is on purpose in order to reset the NRPN number afterwards, just to ensure that the receiving device doesn't stay in limbo.

**Comment by sletz** [comment]
OK I see. Thanks !
