### ISSUE TITLE
How to use it on Linux

### ISSUE THREAD

**Issue by basementmedia2** [gbevin/SendMIDI#23]
Hi,

i#m very glad that i have found this script.
But i wonder how to use it on linux (Ubuntu Studio 18.04.)
i have unpacked the files and now have the file "sendmidi" (and the readme's).
i have tried opening the terminal in the folder of this file and run "sendmidi list" but the terminal says "sendmidi: command not found"

Can you help me to get this thing running?

Best regards
Daniel

**Comment by gbevin** [comment]
Any OS looks up executables through the standard paths, just unzipping it doesn't make Linux aware of where it is. Either put it in /usr/local/bin or execute it with ./sendmidi when the unzipped folder is your current directory, or add that folder to your path. All this is standard Linux usage and you can find plenty of information online about it.

**Comment by basementmedia2** [comment]
Hi,

Thanx for your help. I am relatively new in using linux and still in learning process.
So thanx again for learning again. 

Best wishes from germany

Daniel
