### ISSUE TITLE
How To Send and Receive SysEx Files

### ISSUE THREAD

**Issue by 0xvividmirage** [gbevin/SendMIDI#24]
Hello, I am trying to backup my Behringer RD-8 data and and load it back in and I am not sure I am doing it right because loading it back in doesn't seem to work. I am using GNU/Linux.

To receivemidi I use:
./receivemidi dev "RD-8 MIDI 1" syx > pattern1.syx

To sendmidi I use:
./sendmidi dev "RD-8 MIDI 1" syx pattern1.syx

Am I doing this correctly?

**Comment by 0xvividmirage** [comment]
I ended up using [SysExxer-NG](https://github.com/linuxmao-org/sysexxer-ng) which works fine and has a GUI.

**Comment by gbevin** [comment]
I added the `syf` command to receivemidi in order to store the sysex dump to a file directly.
