### ISSUE TITLE
Inherent problem with Bitwig on Linux

### ISSUE THREAD

**Issue by dreamcat4** [gbevin/SendMIDI#28]
Hi there. I want to say thank you for providing such a great tool. It appears which you are calling the `juce` library from Trackon stuff. Anyhow onto my problem... it is really more of an observation about the lack of 'good enough' midi support in Bitwig.

So here goes:

* On linux Bitwig does not have proper MIDI support
* This is especially true through Jack audio server
* It requires loading up the linux kernel virtual midi port driver
* Then a convoluted series on interconnections in jack
* This can be saved in the jack GUI tool known as `qjackctl`
* Finally after passing through the linux virtual MIDI device, then alsa audio stack, then through Jack audio stack
* The midi signals finally reaches Bitwig Studio
* And it can be used as regular MIDI Generic keyboard, notes instrument input.

Great!
I finally got there.

Unfortunately there is a problem! You see once `sendmidi` program quits... then the virtual midi device is destroyed. And it disappears in ALSA, and in JACK. Breaking that 'too complicated' daisy chain of links into Bitwig.

So what `qjackctl` GUI program provides is a 'Session' feature to save your patchbay connections. And then automatically re-link the devices. Once they appear again. Unfortunately this is done by POLLING. And is not fast enough.

So when `sendmidi` is next invoked to shoot off a midi command. By running: `sendmidi virt SendMIDI-dev1 on e6 123`

Then it has done these actions:

* Created the virtual midi device 
* Made the note on command on the midi bus
* Torn down and destroyed the virtual midi device
* Exited

All before the `qjackctl` has had it's next polling time, and so it never noticed the virtual midi device has appeared. Because it's already gone again.

The consequence is that all of the midi commands were missed / dropped from the signal chain. And Bitwig never received anything.

So obviously I already know about the `--` flag to read from `stdin`. That is meant to be the solution. However I also wish that it could be much simpler. Because to pipe from a command to the `stdin` then requires launching in background, listening on a socket, and also they writing another little program to made it's request to that open listening socket. Or with an existing tool like telnet, socat, or whatever.

The main problem still exists on linux. Where the complicated chain of devices. Which is rather too fragile and prone to breakage. The complex configuration requires a number of different pieces all to be working 'just exactly so'. Otherwise you get nothing. So It would be nice to avoid all that somehow. Or at least make it more robust / hide some of that complexity with another tool.

So I'm very grateful for this tool. However there still remains some missing 'glue' to actually make It work well enough for the Bitwig linux.

I just hope my comments can shed light for anybody else. Who is trying to control Bitwig Studio on linux from the commandline. Because this is the only way it seems. I have found nothing else online that actually works.

You then of course map your midi signals to different controls etc. with the MIDI config inside of Bitwig. Just like Ableton, the controls change color and you select one at a time to create each for a MIDI mapping.

What a total PITA. It's no fault of your tool of course. I just wanted to show the real world situation. And hopefully that helps others to understand what else is missing to get it working. Outside of the `sendmidi` program alone. Which I think is a great little tool. Just wanted to actually to use it !

ATM the path of least resistance seems to be 'create a new service in systemd'. For `sendmidi` to listen all the time on a socket. And launch that process when the Jack audio server launches. From the existing hook to run the startup script in `qjackctl` on 'Jack Start'. Which is the same place where it is already launching `a2jmidid &`.

Of course then also need a command to run from terminal. That will `cat` or `pipe` the commands to that listening `sendmidi` program that was converted into a long running service. Have not thought about all yet.

Perhaps (maybe) a small, and stupid web API could listen on TCP. For example if to send a command from other devices on LAN. Such as an RPI / phone app, or home automation smart switch. For other remote control from other machines and devices.... that might be useful too. So long as it is not too complicated. After all - we only need to send some simple commandline. Same as the existing `sendmidi --help`. Just executing it remotely instead of locally.

Of course if anybody else has any suggestions / comments. Then I am very glad to hear them.

Otherwise it's too complicated and I might give up again. Tried to do this many times, never got 'this far' before.

It's quite lousy really because the thing missing (last time I failed) was because the linux kernel module was not loaded. Becuase I had put the line 

```
snd-virmidi midi_devs=1
```

into `/etc/modules` file. With a `-` dash instead of an `_` underscore. It should have been:

```
snd_virmidi midi_devs=1
```

See the difference? Perhaps not? Well I did not see that either until just now. But it's the difference between all of this 'too complicated' MIDI configurations stuff either working or not working. Such a stupid mistake. I have to destroy and tear everything down now to reboot and check that it worked. Such a fragile porcelain.

**Comment by gbevin** [comment]
Creating long lasting MIDI devices is not really sendmidi's responsibility. It sounds to me that you need to make sure you have a stable set of MIDI ports available to communicate and then use sendmidi for particular tasks.

**Comment by dreamcat4** [comment]
many thanks for replying and giving these advice. the issue was left right there so i will eventually be trying again. but taking your suggestion in some new hopes it may help. however the next time will be with pipewire instead of jack. another hope to maybe be improved too

appreciate the response & good day

**Comment by gbevin** [comment]
I just thought of a possible solution though, you can use timestamp offsets (see readme) to send midi messages at a later time. So if it takes a while for the virtual device to be detected, you could use that to send the messages later.
