### ISSUE TITLE
Create brew formula

### ISSUE THREAD

**Issue by TheBaronHimself** [gbevin/SendMIDI#3]
Thanks for creating this excellent tool. I imagine many people will be interested. 

I think it would be helpful to have a Homebrew formula. What do you think?

**Comment by gbevin** [comment]
I submitted a brew formula, hope they will integrate it soon.

**Comment by TheBaronHimself** [comment]
Thank you :).

**Comment by TheBaronHimself** [comment]
Interesting: Apparently SendMIDI's GitHub repo is too new and not notable enough. See error messages here:

https://bot.brew.sh/job/Homebrew%20Core/14742/version=el_capitan/testReport/brew-test-bot/el_capitan/audit_sendmidi___online___new_formula/

Let's hope it grows quickly.

Also, there seems to be an issue with the Yosemite build:

https://bot.brew.sh/job/Homebrew%20Core/14742/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit_sendmidi___online___new_formula/

https://bot.brew.sh/job/Homebrew%20Core/14742/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_sendmidi/

**Comment by gbevin** [comment]
Yeah, they gave me some good comments on the pull request also ... let's wait a little while.

**Comment by TheBaronHimself** [comment]
Should the issue be reopened?

**Comment by gbevin** [comment]
I guess it should ...

**Comment by gbevin** [comment]
Using a custom tap for now, install with:
`brew install gbevin/tools/sendmidi`
