### ISSUE TITLE
No Valid Midi output port was specified for some of the messages

### ISSUE THREAD

**Issue by simply-Gamic** [gbevin/SendMIDI#30]
![Desktop Screenshot 2021 03 13 - 15 35 49 94](https://user-images.githubusercontent.com/80588359/111033510-ec60a800-8411-11eb-9f1b-2e505ea7c7d7.png)

I get this message and I can't do anything about it. The midi port of my launchpad is there but everytime I want to send a midi note I get this :No Valid Midi output port was specified for some of the messages
Already tried changing the name, channel and everything, but nothing works..

**Comment by gbevin** [comment]
Since your midi port includes spaces you have to enclose it in double quotes.

**Comment by simply-Gamic** [comment]
Thank you for this fast answer ^^
I'll try putting it in double qoutes.
