### ISSUE TITLE
[Info] Send / ReceiveMIDI available for Fedora

### ISSUE THREAD

**Issue by ycollet** [gbevin/SendMIDI#31]
Hello,
Just wanted to let you know that Send/ReceiveMIDI are now available on Fedora 32 / 33 64 bits.
They are on this COPR repository:
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/
And the spec files are here:
https://github.com/ycollet/fedora-spec

**Comment by gbevin** [comment]
Awesome, thanks for the info!
