### ISSUE TITLE
send CC7 (volume) messages with "relative values"?

### ISSUE THREAD

**Issue by capoei** [gbevin/SendMIDI#32]
I know this is not how midi is intended to work, but would it be possible to make a comand with CC7 with something like (for example) -1 where it would consider the last value and lower it by 1? for example. I first "absolutly" set CC7 to 115. than I would use a "relative" comand with -1 and it would set CC7 to 114.

**Comment by gbevin** [comment]
Like you rightfully said, this seems out of scope for SendMIDI. However, since SendMIDI allows you to use shell scripting to send MIDI, your functionality could be relatively easily achieved by scripting your functionality with bash or another scripting language.
