### ISSUE TITLE
clock bpm beats  - suggestion

### ISSUE THREAD

**Issue by pklum** [gbevin/SendMIDI#34]
Hello,
I really like SendMIDI, great program!

I have a proposal. I own a Roland SPD-SX drum module and have discovered that only 2 beats (48 pulses) in the clock command, are not enough for it to set the correct tempo. It takes 6-8 beats for it to set the correct tempo. It would be nice if you could enter two arguments for the clock command "bpm" and "beats". Where "beats" is the number of beats to be sent to the device. (clock bpm beats)

Best Regards, Peter

**Comment by gbevin** [comment]
Thanks for the suggestion, the easy way it to simply repeat the clock command:
`sendmidi dev usb clock 120 clock 120 clock 120`

**Comment by pklum** [comment]
Thanks for the quick reply.
I tested your proposal and it works well, Thank you!!!

Best Regards, Peter
