### ISSUE TITLE
Making on raspberry pie

### ISSUE THREAD

**Issue by abteenz** [gbevin/SendMIDI#35]
Hi,

I had to run
make LDFLAGS=-latomic.
in order for it to work on raspberry pie.

Just letting you know.

Amazing tool! Finally I can use my usb foot controller and xdotool in combination with your program to control my boss dr-880

Thanks!

**Comment by touchgadget** [comment]
The release package for ARM is for 64-bit arch so do not work on Raspberry Pi OS (formerly known as Raspbian).

See message #35. `make LDFLAGS=-latomic` works for me on RPi OS bullseye(32-bit). This works for ReceiveMIDI also.

**Comment by gbevin** [comment]
Fixed in next release
