### ISSUE TITLE
can't make sendMidi work on Raspbery PI3b+

### ISSUE THREAD

**Issue by bareOwl** [gbevin/SendMIDI#36]
Hello,

I Successfully installed sendmidi on a linux desktop and i find it quite usefull.
I'm trying to do the same on raspberry, however it doesn't work.

If i install the arm package and launch sendmidi, this is what i get :
/sendmidi 
-bash: ./sendmidi: cannot execute binary file: Exec format error

If i try to build it from the source, i get a lot of "changed in GCC 7.1" errors. For example :
/usr/include/c++/8/bits/stl_heap.h:222:14: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<juce::NetworkServiceDiscovery::Service*, std::vector<juce::NetworkServiceDiscovery::Service> >' changed in GCC 7.1

Could you provide any help ?

Regards

**Comment by gbevin** [comment]
You probably should compile it from source
