### ISSUE TITLE
Can't find output port on Windows with "quotations"

### ISSUE THREAD

**Issue by BlackCatTB** [gbevin/SendMIDI#37]
Hi
great application really like it!
so I'm trying to send cc 40 01 to my apc mini, but it always throws me an error, firstly I thought it cant find it due to other programs using it like voicemeter potato or macro buttons but it can which is very confusing please help
Thank you!

![image](https://user-images.githubusercontent.com/31024398/157365426-badcadc8-2736-4e15-be9e-087edbddcf76.png)

**Comment by gbevin** [comment]
Yes it might be that another program is already using it. FYI it's not necessary to specify the full name, you can just write a part that uniquely matches and sendmidi will figure it out. You can for instance use `sendmidi dev apc cc 40 03` and it will use APC MINI as the device.
