### ISSUE TITLE
Call from KM Shell Script?

### ISSUE THREAD

**Issue by noisyneil** [gbevin/SendMIDI#39]
This is more of a tip for other users than an issue. I started out by asking how to do this, then I figured it out and thought I'd edit this comment and share my findings. 

Keyboard Maestro can send midi but can's select output ports, so Sendmidi is a godsend!

For anyone who wants to use Sendmidi from KM's _Execute a Shell Script_ action, you need to set the path to the Sendmidi installation folder, as part of the script. 

In this example, I'm sending a program change to a guitar pedal to change its preset. The first line sets the installation path and with this included, Sendmidi works beautifully!! 

```
export PATH=/usr/local/bin:$PATH;
sendmidi dev "HX Stomp" ch 15 pc "$KMVAR_Local__PresetNumber"
```

**Comment by gbevin** [comment]
You can also just call it directly like this:
`/usr/local/bin/sendmidi dev "HX Stomp" ch 15 pc "$KMVAR_Local__PresetNumber"`
