### ISSUE TITLE
error installing with brew

### ISSUE THREAD

**Issue by tooh** [gbevin/SendMIDI#40]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Latest xcode is installed and latest command line tools

**Comment by tooh** [comment]
Solution

`sudo` xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by gbevin** [comment]
Yes, that's part of using the Xcode toolset on the command line. Brew should take care of that.
