### ISSUE TITLE
MIDI channel needs to be specified before command

### ISSUE THREAD

**Issue by bwagner** [gbevin/SendMIDI#43]
sendmidi v1.0.15 on macOS 10.14.6 (Mojave):

MIDI channel needs to be specified before command, e.g.:
`sendmidi dev um ch 2  cc 110 127`
When using:
`sendmidi dev um cc 110 127 ch 2 `
the channel is silently ignored.
This might be worth mentioning in the help text (or the argument parser made more lenient, or an error generated when channel is being set in the wrong position on the command line.)

**Comment by gbevin** [comment]
that's by design, the arguments have an order, you can send multiple ccs on multiple channels, if the channel is omitted, it defaults to 1 as documented
