### ISSUE TITLE
Linux binaries missing in Releases

### ISSUE THREAD

**Issue by CodexHere** [gbevin/SendMIDI#49]
Looks like at some point Linux binaries stopped being produced for releases.

Can you update the releases with Linux builds, or proper instructions on how to build with dependencies?

**Comment by gbevin** [comment]
It's not feasible for me to build Linux binaries for all possible distributions and platforms. Please build it from source or ask your favorite distribution to include it as a package.

**Comment by CodexHere** [comment]
Sorry, just to be clear I wasn't meaning builds for a package, just the binaries as they were building before version `1.2.0`.

I guess I'll have to figure out how to build it myself since there's no documentation or stated dependencies.

**Comment by gbevin** [comment]
Providing single binaries on Linux is just not feasible for all distributions and platforms
