### ISSUE TITLE
XCODE is required for BREW

### ISSUE THREAD

**Issue by bilekt3** [gbevin/SendMIDI#5]
I do not want Xcode to be installed, but I would like to use convenience of brew. 

Please it is possible to compile only wit CLI tools?

`
sendmidi: A full installation of Xcode.app is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
`

**Comment by gbevin** [comment]
I don't think this is possible, Xcode provided the whole compiler infrastructure, the CLI tools are just a way to drive that from the command line.
