### ISSUE TITLE
send sustain (and maybe other pedals) on and off signals

### ISSUE THREAD

**Issue by rogergithubbing** [gbevin/SendMIDI#51]
Hello, 

Is it possible to send sustain (and maybe other pedals) on and off signals ?

My keyboard does not have ability to use pedals, and I am trying my best to find a solution to use some trick to send the sustain on and off signals to ableton, but I didn't find a solution.

I've thought that if I assign some keys to execute your program I could use that feature... I don't know if that could be possible at all...

Thanks in advance !

**Comment by gbevin** [comment]
cc64 is sustain pedal
cc66 is sostenuto pedal

...

so this is totally possible with send midi already
