### ISSUE TITLE
Add support to send sysex messages read from a File

### ISSUE THREAD

**Issue by Pseudomoo** [gbevin/SendMIDI#6]
Hi,

It would be great to have the facility to send sysex messages from a File path... 
I have a Mutable Instruments Shruthi, and have a bunch of presets on my filesystem, as binary sysex files. 
If this utility could send sysex bytes to a named midi device, I could set up a simple Shell Association on .syx files, or have it as a right-click option in Windows Explorer ("Send to Shruthi").

Suggested Usage:
sysexfile <path-to-file>

Looking at:
https://www.juce.com/doc/classFile

Looks like we could use:
bool loadFileAsData (MemoryBlock &result) const

I think the impl might be something like this new switch block:
            case SYSTEM_EXCLUSIVE_FILE:
            {
                File file = File::getCurrentWorkingDirectory().getChildFile(param);
                if (!file.existsAsFile())
                {
                    file = new File(param);
                }
                if (file.existsAsFile())
                {
                    MemoryBlock mem(file.getSize(), true); // need to downcast the int64 return from getSize()?
                    bool readSuccess = file.loadFileAsData(&mem); //do I need to pass the pointer??
                    if (readSuccess) {
                        sendMidiMessage(MidiMessage::createSysExMessage(mem.getData(), mem.getSize()));
                    } else {
                        //flag can't read file param  
                    }
                } else {
                    //flag FileNotFound for param arg
                }
                break;
            }

I know Java, used to know C++, but unfortunately I have no idea how to set up a free C++ compiler on my machine (Win7 32-bit) with the Juce libs to link to build the exe...

**Comment by gbevin** [comment]
That's a good idea! I'll look into adding this soon.

**Comment by Pseudomoo** [comment]
Great, thank you!

**Comment by gbevin** [comment]
SendMIDI 1.0.6 now has the syf command to send .syx files

**Comment by Pseudomoo** [comment]
Thank you! Will test tonight, Win7 32-bit.

**Comment by Pseudomoo** [comment]
Works great on Win7 32-bit. 
I added a new Context menu to .syx files in Windows Explorer - can upload patches to my two Shruthi now directly from the context of the OS file browser. 
Great news! Especially since my sequencer (Ableton) actively filters out sysex data!

Thank you!

**Comment by gbevin** [comment]
Thanks for the report @Pseudomoo, great to hear that it's working well for you! :-)
