### ISSUE TITLE
Query about SysEx command format

### ISSUE THREAD

**Issue by wemmackie** [gbevin/SendMIDI#7]
Hello

Could you give an example of a SysEx command please, either in decimal or hex, or ideally one of each?  I've been trying to send SysEx parameter change commands to a Yamaha FS1R and haven't been able to get anything working. 

I've tried these ways so far:
sendmidi dev "iConnectMIDI4+ DIN 1" syx hex f0 43 10 5e 10 00 10 00 7f f7
sendmidi dev "iConnectMIDI4+ DIN 1" syx [f0H 43H 10H 5eH 10H 00H 10H 00H 7fH f7H]
sendmidi dev "iConnectMIDI4+ DIN 1" syx {f0H 43H 10H 5eH 10H 00H 10H 00H 7fH f7H}

... and I've tried converting to decimal as well and dropping the 'hex'/'H' obviously.  MIDI cc, note on, etc. are working fine from SendMIDI and I know that the above SysEx command works (volume change), because I've sent it effectively from a VST.

Apologies if I'm making an obvious mistake but I can't think of anything else to try.

**Comment by gbevin** [comment]
SendMIDI will add the f0 and f7 bytes at the beginning and end itself, which is what makes it a sysex message. So you just need the payload to be written.

This should work:
sendmidi dev "iConnectMIDI4+ DIN 1" syx hex 43 10 5e 10 00 10 00 7f

**Comment by wemmackie** [comment]
Thanks for your reply. It still doesn't work. I've tried with other commands that I've managed to send successfully from the FS1R editor VST (called I lov FS1R).

**Comment by gbevin** [comment]
Sorry, I didn't spot the hex after the syx command, which effectively terminates it.
This should work:
sendmidi dev "iConnectMIDI4+ DIN 1" hex syx 43 10 5e 10 00 10 00 7f

I will improve this in the next version so that the hex and dec commands are more permissive and can be used anywhere inline without interrupting other commands.

**Comment by gbevin** [comment]
SendMIDI 1.0.6 is now out which allows dec and hex commands to be inline anywhere without interrupting the active command. So the example of 4 days ago now works also.

**Comment by wemmackie** [comment]
Great, many thanks! Working fine now.
