### ISSUE TITLE
hex syx 0D

### ISSUE THREAD

**Issue by bsoundnz** [gbevin/SendMIDI#8]
Hi there.  I emailed you a few days ago (before I realised there was an issues list here - apologies).
After reading some of the other resolved issues I realised I didn't need to put F7 at the end of a syx message (that was causing the 7F byte).   I still though cannot get your wonderful little tool to send hex syx 0D.  It arrives as F0 00 F7 every time.  0C and 0E work fine.  
Thanks!

**Comment by gbevin** [comment]
Hah, great catch and interesting bug. What is happening is that it's interpreting the final D to indicate that it's a decimal number. I should have though about that when including that feature. I'll have to think about how to properly fix it. For the time being you can write it as 0Dh to force it being hex.

**Comment by gbevin** [comment]
I fixed the problem by changing the decimal suffix into M instead of D. Preparing a new release with that. Thanks again for reporting this!

**Comment by gbevin** [comment]
SendMIDI 1.0.7 is now available with the described change.
